### ISSUE TITLE
mobilenetssd使用的是那个训练代码

### ISSUE THREAD

**Issue by hyaihjq** [MirrorYuChen/ncnn_object_detector#1]

**Comment by MirrorYuChen** [comment]
用的chuanqi305的caffe模型：
https://github.com/chuanqi305/MobileNet-SSD

**Comment by hyaihjq** [comment]
> 用的chuanqi305的caffe模型：
> https://github.com/chuanqi305/MobileNet-SSD

谢谢

**Comment by MirrorYuChen** [comment]
嗯嗯，没事，这个项目没时间更新，后面会再重构一下，把一些常见的模型都加进去，那我现在把issue关了啦~
